### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed4#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos [_issues_](https://github.com/Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed4/issues) nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by ElenaMLopez** [comment]
# Presentación

Hola! Me llamo **Elena**, soy programadora junior de front en NC43Tech. Colaboro con varias comunidades aunque es la de OSW a la que más tiempo dedico, porque me parece una comunidad increíble y llena de talento. 

Actualmente me encargo de la organización del Hacker Space de dicha comunidad y si me ves con cara traviesa huye, porque te voy a liar para algo jejeje. 

También estoy muy interesada en la ciberseguridad, y estoy deseando aprender a dominar bien JavaScript, es un reto personal y como premio aprenderé python. Ambos lenguajes pueden ayudarme mucho en el camino del hacking y el pentesting. 

Podéis encontrarme en muchísimos eventos y adoro dar charlas. 

Peace Love and open source. 

![Hello!](https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy-downsized.gif)

**Comment by ElenaMLopez** [comment]
Spell corrections
Add a Giphy in your markdow document: You can add a animated giphy selecting a gif from giphy.com, in the media tab, selecting the link 'small', and just insert it like a image. :wink:

**Comment by FranciscoValdesoiro** [comment]
# Presentación

Hola a todos! Soy Fran, trabajo como Programador Xamarin y .Net, Soy Guilder del RedTeam en OSW y colaboro activamente en su HackerSpace.

En mi tiempo libre he desarrollado proyectos móviles trasteando con tecnologías de realidad virtual, realidad aumentada y juegos de pc y movil con unity ademas de otros motores gráficos. 

Solo llevo desarrollando un año y pico pero me encanta trastear y experimentar con nuevas tecnologías.

Estoy encantado de estar compartiendo este curso con vosotros ^^.
