### ISSUE TITLE
Preocúpate de tu privacidad

### ISSUE THREAD

**Issue by ElenaMLopez** [Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed4#25]
## Recursos para proteger tu privacidad:

https://amiunique.org/: Explicación de que es el 'fingerprint' y como se realiza. [Ejemplo](https://amiunique.org/fp)

**Comment by UlisesGascon** [comment]
Fingerprint
- https://panopticlick.eff.org/static/browser-uniqueness.pdf
- https://panopticlick.eff.org/
